#!/usr/bin/env bash
#
# launch.sh — clone the app, build, start under HTTPS.
#
# Run AFTER bootstrap.sh has succeeded AND you've added the deploy key
# (printed at the end of bootstrap) to your GitHub repo.
#
# Idempotent — for app updates, just re-run.
#
# Usage:  ./launch.sh

set -euo pipefail

# ─── Configuration (edit if your IP or repo changes) ───────────────────────
REPO_SSH="git@github.com:shashank6633/eventcover-wallet.git"
APP_DIR="/srv/eventcover"
DATA_DIR="/var/eventcover/data"
HOSTNAME="34-47-218-105.sslip.io"
# ───────────────────────────────────────────────────────────────────────────

echo
echo "==> 1/8  Testing SSH access to GitHub"
# `ssh -T git@github.com` returns exit 1 with the "successfully authenticated"
# message — that's success, not a failure.
ssh -T -o StrictHostKeyChecking=accept-new git@github.com 2>&1 | head -2 || true
if ssh -T -o BatchMode=yes git@github.com 2>&1 | grep -qi "Permission denied"; then
  echo "    GitHub SSH auth failed. Re-check the deploy key on GitHub."
  exit 1
fi

echo
echo "==> 2/8  Cloning / updating the repo"
if [[ -d "$APP_DIR/.git" ]]; then
  cd "$APP_DIR"
  git fetch origin
  git reset --hard origin/main
  echo "    Updated to $(git rev-parse --short HEAD)"
else
  git clone "$REPO_SSH" "$APP_DIR"
  cd "$APP_DIR"
  echo "    Cloned at $(git rev-parse --short HEAD)"
fi

echo
echo "==> 3/8  npm install"
npm install --legacy-peer-deps --no-audit --no-fund

echo
echo "==> 4/8  .env file"
if [[ ! -f "$APP_DIR/.env" ]]; then
  cat > "$APP_DIR/.env" <<EOF
# Generated by launch.sh on $(date)
NODE_ENV=production
PORT=3000

# Public URL Interakt will fetch PDFs from
PUBLIC_BASE_URL=https://$HOSTNAME

# HMAC secret for signed PDF download URLs
WALLET_PASS_SECRET=$(openssl rand -hex 32)

# Session signing secret
SESSION_SECRET=$(openssl rand -hex 32)
EOF
  echo "    Wrote $APP_DIR/.env with fresh secrets"
else
  echo "    .env already exists — keeping it"
fi

echo
echo "==> 5/8  Symlink SQLite data dir → persistent /var location"
if [[ ! -L "$APP_DIR/data" ]]; then
  rm -rf "$APP_DIR/data" 2>/dev/null || true
  ln -s "$DATA_DIR" "$APP_DIR/data"
  echo "    $APP_DIR/data → $DATA_DIR"
fi

echo
echo "==> 6/8  Building Next.js"
npm run build

echo
echo "==> 7/8  Caddy → HTTPS reverse proxy"
sudo tee /etc/caddy/Caddyfile >/dev/null <<EOF
$HOSTNAME {
  reverse_proxy localhost:3000
  encode gzip
  log {
    output file /var/log/caddy/access.log
    format console
  }
}
EOF
sudo systemctl reload caddy 2>/dev/null || sudo systemctl restart caddy
echo "    Caddy is serving https://$HOSTNAME → localhost:3000"

echo
echo "==> 8/8  Start app under pm2"
cd "$APP_DIR"
pm2 delete eventcover 2>/dev/null || true
pm2 start npm --name eventcover -- start
pm2 save

# Enable pm2 auto-start on reboot (idempotent — pm2 startup prints the command,
# we capture it and run with sudo).
echo
echo "    Enabling pm2 auto-start on reboot…"
STARTUP_CMD=$(pm2 startup systemd -u "$USER" --hp "$HOME" 2>&1 | grep '^sudo env' || true)
if [[ -n "$STARTUP_CMD" ]]; then
  eval "$STARTUP_CMD"
fi

cat <<BANNER

===========================================================================
  Deployment complete!
===========================================================================

  Open:  https://$HOSTNAME

(Wait ~30-60 seconds for Caddy to obtain a Let's Encrypt cert on first hit.
 The first request might show a TLS warning that goes away after the cert
 is issued.)

  pm2 status                — see app state
  pm2 logs eventcover       — tail Next.js logs (Ctrl-C to exit)
  sudo journalctl -u caddy  — Caddy logs
  pm2 restart eventcover    — restart after env change

To re-deploy after a code change:
  cd $APP_DIR
  git pull
  npm install --legacy-peer-deps
  npm run build
  pm2 restart eventcover

BANNER
