'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { DEFAULT_TICKET_DESIGN, normalizeHexColor, type TicketDesign, type TicketLayout } from '@/lib/ticket-design';
import type { WizardState } from './types';

/**
 * Ticket Design section (Phase 4).
 *
 * Lets the host customize the wallet pass PNG that customers see on WhatsApp
 * and at the door. The PNG is generated by src/lib/pdf/pass-image.ts which
 * accepts a TicketDesign override; the values configured here ride along
 * with the normal wizard Save (PATCH /api/events/[id] { ticket_design }).
 *
 * UI:
 *   • Two-column on desktop (controls on left, live preview on right),
 *     stacked on mobile.
 *   • Live preview re-renders by POSTing to
 *     /api/events/[id]/ticket-design/preview with the current draft. The
 *     response is an image/png blob → object URL → <img>. Debounced 400ms.
 *   • No persistence happens on color changes — only on the wizard Save
 *     button at the top of the page. The preview endpoint is read-only.
 *
 * Falls back to a "Save the event first" prompt when the event hasn't been
 * persisted yet (no event id = no preview endpoint to hit).
 */

interface Props {
  state: WizardState;
  onChange: (patch: Partial<WizardState>) => void;
  /** May be null on a brand-new event that hasn't been saved yet. */
  eventId: string | null;
}

const BRAND = '#C1551A';

export function SectionTicketDesign({ state, onChange, eventId }: Props) {
  const design = state.ticket_design;

  const patch = useCallback(
    (p: Partial<TicketDesign>) => {
      onChange({ ticket_design: { ...design, ...p } });
    },
    [design, onChange],
  );

  return (
    <div className="space-y-4">
      <div className="card space-y-2">
        <header>
          <h2 className="text-lg font-semibold text-slate-900">Ticket Design</h2>
          <p className="text-sm text-slate-500 mt-1">
            Customize the wallet pass PNG that customers receive on WhatsApp.
            Changes go live the next time you click <span className="font-semibold text-slate-700">Save</span> at the top.
          </p>
        </header>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* ─── Left column: editor ─────────────────────────────────────── */}
        <div className="card space-y-5">
          <div>
            <div className="text-[11px] uppercase tracking-widest text-slate-500 mb-2">
              Colors
            </div>
            <div className="space-y-3">
              <ColorRow
                label="Background"
                hint="Header band start color"
                value={design.background}
                fallback={DEFAULT_TICKET_DESIGN.background}
                onChange={(v) => patch({ background: v })}
              />
              <ColorRow
                label="Accent"
                hint="Header band end color (gradient)"
                value={design.accent}
                fallback={DEFAULT_TICKET_DESIGN.accent}
                onChange={(v) => patch({ accent: v })}
              />
              <ColorRow
                label="Text"
                hint="Primary text + QR pixels"
                value={design.text}
                fallback={DEFAULT_TICKET_DESIGN.text}
                onChange={(v) => patch({ text: v })}
              />
            </div>
          </div>

          <div className="pt-4 border-t border-slate-100">
            <div className="text-[11px] uppercase tracking-widest text-slate-500 mb-2">
              Visibility
            </div>
            <div className="space-y-2">
              <Toggle
                label="Show logo / header band"
                hint="Off renders a thin brand bar instead of the full band"
                checked={design.show_logo}
                onChange={(v) => patch({ show_logo: v })}
              />
              <Toggle
                label="Show event date"
                hint="Hides the date sub-line under the event name"
                checked={design.show_date}
                onChange={(v) => patch({ show_date: v })}
              />
            </div>
          </div>

          <div className="pt-4 border-t border-slate-100">
            <div className="text-[11px] uppercase tracking-widest text-slate-500 mb-2">
              Layout
            </div>
            <LayoutPicker
              value={design.layout}
              onChange={(v) => patch({ layout: v })}
            />
          </div>

          <div className="pt-4 border-t border-slate-100">
            <button
              type="button"
              onClick={() => onChange({ ticket_design: { ...DEFAULT_TICKET_DESIGN } })}
              className="text-xs text-brand-600 hover:text-brand-700 inline-flex items-center gap-1"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M3 12a9 9 0 1 0 3-6.7"/>
                <path d="M3 4v5h5"/>
              </svg>
              Reset to brand defaults
            </button>
            <p className="text-[11px] text-slate-400 mt-1">
              Rust palette ({BRAND}), both toggles on, classic layout.
            </p>
          </div>
        </div>

        {/* ─── Right column: live preview ──────────────────────────────── */}
        <div className="card">
          <div className="text-[11px] uppercase tracking-widest text-slate-500 mb-2">
            Live preview
          </div>
          {eventId ? (
            <LivePreview eventId={eventId} design={design} />
          ) : (
            <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/50 px-4 py-10 text-center">
              <div className="text-sm text-slate-600 font-medium">
                Save the event first.
              </div>
              <div className="text-[12px] text-slate-500 mt-1">
                The preview renders a real wallet PNG using this event&apos;s name + date,
                so we need an event id before it can run.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ─── Color row ────────────────────────────────────────────────────────── */

function ColorRow({
  label,
  hint,
  value,
  fallback,
  onChange,
}: {
  label: string;
  hint: string;
  value: string;
  fallback: string;
  onChange: (hex: string) => void;
}) {
  // The <input type="color"> only accepts lowercase #rrggbb. Our state stores
  // uppercase (normalizeHexColor uppercases) — normalize both directions so
  // the swatch reflects the saved value without forcing a re-fetch.
  const safe = normalizeHexColor(value, fallback);
  const swatchValue = safe.toLowerCase();

  const [text, setText] = useState(safe);
  useEffect(() => { setText(safe); }, [safe]);

  return (
    <div className="grid grid-cols-[auto,1fr,auto] gap-3 items-center">
      <input
        type="color"
        value={swatchValue}
        onChange={(e) => onChange(normalizeHexColor(e.target.value, fallback))}
        className="w-10 h-10 rounded-md border border-slate-200 cursor-pointer bg-white p-0.5"
        aria-label={`${label} color picker`}
      />
      <div>
        <div className="text-sm font-medium text-slate-800">{label}</div>
        <div className="text-[11px] text-slate-500">{hint}</div>
      </div>
      <input
        type="text"
        value={text}
        onChange={(e) => setText(e.target.value)}
        onBlur={() => {
          const cleaned = normalizeHexColor(text, fallback);
          setText(cleaned);
          if (cleaned !== safe) onChange(cleaned);
        }}
        onKeyDown={(e) => {
          if (e.key === 'Enter') e.currentTarget.blur();
          else if (e.key === 'Escape') { setText(safe); e.currentTarget.blur(); }
        }}
        className="w-24 text-xs font-mono px-2 py-1.5 rounded-md border border-slate-200 focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-100"
        maxLength={7}
        aria-label={`${label} hex value`}
      />
    </div>
  );
}

/* ─── Toggle ───────────────────────────────────────────────────────────── */

function Toggle({
  label,
  hint,
  checked,
  onChange,
}: {
  label: string;
  hint: string;
  checked: boolean;
  onChange: (v: boolean) => void;
}) {
  return (
    <label className="flex items-start gap-3 cursor-pointer group">
      <button
        type="button"
        role="switch"
        aria-checked={checked}
        onClick={() => onChange(!checked)}
        className={`relative inline-flex h-5 w-9 shrink-0 mt-0.5 rounded-full transition-colors ${
          checked ? 'bg-brand-500' : 'bg-slate-300'
        }`}
      >
        <span
          className={`absolute top-0.5 left-0.5 h-4 w-4 rounded-full bg-white shadow transition-transform ${
            checked ? 'translate-x-4' : 'translate-x-0'
          }`}
        />
      </button>
      <div className="flex-1 min-w-0">
        <div className="text-sm font-medium text-slate-800 group-hover:text-slate-900">
          {label}
        </div>
        <div className="text-[11px] text-slate-500">{hint}</div>
      </div>
    </label>
  );
}

/* ─── Layout picker ────────────────────────────────────────────────────── */

function LayoutPicker({
  value,
  onChange,
}: {
  value: TicketLayout;
  onChange: (v: TicketLayout) => void;
}) {
  const opts: { value: TicketLayout; label: string; hint: string }[] = [
    { value: 'classic', label: 'Classic', hint: 'Stacked header + QR card' },
    { value: 'minimal', label: 'Minimal', hint: 'No header band, smaller QR' },
  ];
  return (
    <div className="grid grid-cols-2 gap-2">
      {opts.map((o) => {
        const active = value === o.value;
        return (
          <button
            key={o.value}
            type="button"
            onClick={() => onChange(o.value)}
            className={`text-left rounded-lg border px-3 py-2.5 transition ${
              active
                ? 'border-brand-500 bg-brand-50 ring-2 ring-brand-100'
                : 'border-slate-200 hover:border-slate-300 bg-white'
            }`}
            aria-pressed={active}
          >
            <div className={`text-sm font-semibold ${active ? 'text-brand-700' : 'text-slate-800'}`}>
              {o.label}
            </div>
            <div className="text-[11px] text-slate-500 mt-0.5">{o.hint}</div>
          </button>
        );
      })}
    </div>
  );
}

/* ─── Live preview ─────────────────────────────────────────────────────── */

/**
 * Posts the current TicketDesign to the preview endpoint and renders the
 * returned PNG. Debounced 400ms so dragging a color slider doesn't drown
 * the server in render requests (matches the architect's rate-limit budget).
 *
 * Resilient to:
 *   • Concurrent fetches  — useRef holds the latest AbortController + bumps
 *                           a request id; stale responses are dropped.
 *   • Object-URL leaks    — every fresh blob revokes the previous URL on
 *                           replacement and on unmount.
 *   • 429 / 5xx errors    — surfaces the message; previous PNG stays
 *                           visible so the host doesn't lose context.
 */
function LivePreview({ eventId, design }: { eventId: string; design: TicketDesign }) {
  const [imgUrl, setImgUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Tracking refs — outlive React's render cycle so we can cancel mid-flight
  // requests and revoke prior object URLs without stale-closure bugs.
  const abortRef = useRef<AbortController | null>(null);
  const lastUrlRef = useRef<string | null>(null);
  const requestSeqRef = useRef(0);

  // Debounce so a color-picker drag doesn't fire one request per pixel of
  // movement. 400ms feels snappy without flooding sharp.
  useEffect(() => {
    const handle = setTimeout(() => {
      const seq = ++requestSeqRef.current;

      // Abort any in-flight request — the new design supersedes it.
      if (abortRef.current) abortRef.current.abort();
      const ctrl = new AbortController();
      abortRef.current = ctrl;

      setLoading(true);
      setError(null);

      fetch(`/api/events/${eventId}/ticket-design/preview`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ticket_design: design }),
        signal: ctrl.signal,
      })
        .then(async (res) => {
          if (!res.ok) {
            // Server returns JSON for errors and PNG for success — sniff
            // Content-Type rather than blindly calling .json().
            const ct = res.headers.get('Content-Type') || '';
            if (ct.includes('application/json')) {
              const j = await res.json().catch(() => ({}));
              throw new Error(j.message || `Preview failed (${res.status})`);
            }
            throw new Error(`Preview failed (${res.status})`);
          }
          return res.blob();
        })
        .then((blob) => {
          // Drop the response if a newer request has already started.
          if (seq !== requestSeqRef.current) return;
          const url = URL.createObjectURL(blob);
          if (lastUrlRef.current) URL.revokeObjectURL(lastUrlRef.current);
          lastUrlRef.current = url;
          setImgUrl(url);
        })
        .catch((e) => {
          if (e?.name === 'AbortError') return;
          if (seq !== requestSeqRef.current) return;
          setError(e instanceof Error ? e.message : 'Preview failed.');
        })
        .finally(() => {
          if (seq === requestSeqRef.current) setLoading(false);
        });
    }, 400);

    return () => clearTimeout(handle);
  }, [eventId, design]);

  // Final cleanup: abort outstanding fetch + revoke the last blob URL.
  useEffect(() => {
    return () => {
      if (abortRef.current) abortRef.current.abort();
      if (lastUrlRef.current) URL.revokeObjectURL(lastUrlRef.current);
    };
  }, []);

  return (
    <div className="space-y-2">
      <div className="relative w-full aspect-[2/3] max-w-[360px] mx-auto rounded-xl overflow-hidden border border-slate-200 bg-slate-50">
        {imgUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={imgUrl}
            alt="Wallet pass preview"
            className="absolute inset-0 w-full h-full object-contain"
            draggable={false}
          />
        ) : !loading && !error ? (
          <div className="absolute inset-0 flex items-center justify-center text-xs text-slate-400">
            Rendering preview…
          </div>
        ) : null}

        {loading && (
          <div className="absolute inset-0 bg-white/60 backdrop-blur-[1px] flex items-center justify-center">
            <Shimmer />
          </div>
        )}
      </div>

      {error && (
        <div className="rounded-lg border border-rose-200 bg-rose-50 text-rose-700 px-3 py-2 text-xs">
          {error}
        </div>
      )}

      <p className="text-[11px] text-slate-400 text-center">
        Sample preview — actual passes use the real guest name + QR.
      </p>
    </div>
  );
}

/* ─── Shimmer ──────────────────────────────────────────────────────────── */

function Shimmer() {
  return (
    <div className="flex items-center gap-2 text-xs text-slate-500">
      <svg className="animate-spin" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 12a9 9 0 1 1-6.219-8.56" />
      </svg>
      Regenerating…
    </div>
  );
}
